# fly.toml app configuration file generated for summer-morning-680 on 2023-07-16T15:36:31+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "summer-morning-680"
primary_region = "arn"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
